services:
    docker-dir-to-b2:
        container_name: Dir-to-B2
        environment:
            - B2_BUCKET=my-container
            - B2_ACCESS_KEY_ID=MYACCESSKEYID
            - B2_SECRET_ACCESS_KEY=3jk2kj3lkll+EXAMPLE/k213jl12k3kj213lkj213ll
            - B2_BACKUP_NAME='yourfilenamehere'
        volumes:
            - /my_local_dir/:/upload/:ro
        image: ghcr.io/legionofone/docker-dir-to-b2:Master
