#!/bin/bash

if [ -z "$BB_BUCKET" ]; then
  echo "WARN: BB_BUCKET is unset";
fi

if [ -z "$BB_ACCESS_KEY_ID" ]; then
  echo "WARN: BB_ACCESS_KEY_ID is unset";
fi

if [ -z "$BB_DEFAULT_REGION" ]; then
  echo "WARN: BB_DEFAULT_REGION is unset";
fi

if [ -z "$BB_SECRET_ACCESS_KEY" ]; then 
  echo "WARN: BB_SECRET_ACCESS_KEY is unset";
fi

# Provide environment variables for the cron script
env | sed 's/^\(.*\)$/export \1/g' > /root/.envs

# Star cron
/usr/sbin/cron

echo Started >> /var/log/cron.log
tail -f /var/log/cron.log
